CarrierWave.configure do |config|
  config.fog_credentials = {
    :aws_access_key_id => 'xxxxxx',
    :aws_secret_access_key => 'yyyyyy',
    :provider => 'AWS'
  }
  config.fog_directory = 'directoryname'
  config.fog_public = true
end